version: '3.8'

services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./client/src/data:/app/data 
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: ../Dockerfile.dev     # 👈 use the one in project root
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app             # live reload
      - /app/node_modules         # prevent overwriting node_modules
    env_file:
      - ./client/.env
    environment:
      - VITE_API_URL=http://localhost:5001
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    restart: unless-stopped
