FROM node:20-alpine

WORKDIR /app

# Copy only package.json first
COPY package*.json ./
RUN npm install

# Copy the rest of the client source
COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
