version: '3.8'

services:
  server:
    build: ./server
    ports:
      - "5001:5000"
    volumes:
      - ./client/src/data:/app/data 
      - /app/node_modules   
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: ../Dockerfile.dev   
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app                 # live reload
      - /app/node_modules             # prevent overwriting node_modules
    env_file:
      - ./client/.env                 # 👈 loads VITE_API_URL into the container
    environment:
      - VITE_API_URL=http://localhost:5001
      - CHOKIDAR_USEPOLLING=true      # helps file watching in Docker
    restart: unless-stopped
